name: Release npm

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: npm install
      - name: Publish package
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npm run release:npm
      - name: Upload packed artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-pack-artifacts
          path: eslint-plugin-hardcode-detect-*.tgz
